### ISSUE TITLE
BigInteger Not Supported?

### ISSUE THREAD

**Issue by NarryG** [rikimaru0345/Ceras#18]
Hey. I swapped out BinaryFormatter for Ceras the other day and the performance gains are incredible, but I have run into one issue. It appears that BigInteger isn't currently supported (it serializes without exception, but deserializes into an empty version of the object). Would it be possible to get support added for it?

**Comment by NarryG** [comment]
Looks like this was on me! I didn't configure it properly.

**Comment by rikimaru0345** [comment]
`BigInteger` has built-in support next version.
The formatter for it is done, but I can't yet commit the changes properly since #16 and https://github.com/rikimaru0345/Ceras/pull/17 still need to be completed first.

**Comment by NarryG** [comment]
Note to self. Don't open issues that late at night because I write them horribly. 

All right so here's the deal. We have a little custom network library that wraps a ton of various things within a generic command format (a wrapper class which has a bunch of metadata and then holds an object). We previously used BinaryFormatter for this but it was stupid slow.  One specific object that's sent across is a few levels deep (Stashkey holds a Blastlayer which holds a list of BlastUnits which each have their own biginteger value within their properties).

The thing that fixed it was setting the default targets to all in the config. I actually had the `[Ceras.MemberConfig(TargetMember.All)]` on all the objects being serialized, but I guess changing the default caused it to do additional stuff? I'm still wrapping my head around the library a bit.

**Comment by rikimaru0345** [comment]
> Note to self. Don't open issues that late at night because I write them horribly.
dont worry about it, happens to me too lol.


> The thing that fixed it was setting the default targets to all in the config. I actually had the [Ceras.MemberConfig(TargetMember.All)] on all the objects being serialized, but I guess changing the default caused it to do additional stuff? I'm still wrapping my head around the library a bit.

Yes that's most likely exactly what happend.
And if you are dealing with a graph where you don't 10000% know every type and its private fields then you probably don't want to include private members just like that.

Now here's the thing, the BigInteger has a private byte array and that's what got serialized, that's why it worked, even though it shouldn't have (well, "shouldn't" hmmm, you know what I mean)

My point is: By changing the global default you may be including tons of stuff that you're not fully aware of (and by you I mean the you in general, like everyone, not you specifically).
And most of the time it might work out perfectly fine because the base framework types are only so complicated, and most of the time pretty "tame".

But there are times when things can go really wrong.

Here's an example, you don't have to read it all if you don't want to, i'll write the quick version below: #11 

So what the link above says is basically: You might be including stuff like `public event Action Bla;` as well, and that in turn includes all sorts of "caught" variables from some labmda expressions, and that includes additional objects and.... you see where this is going.

Anyway, BigInteger support is done, just not released yet because I got some more stuff to do before the next version, but I really hope it helps.

So my tip for more complicated projects (more complicated = bigger than a simple example or demo) is to only annotate things with MemberConfig. But then again there are probably cases where it makes sense to turn it on even for large objects. It all depends on the situation, it's just meant as a general guidline :P

And don't worry about asking stuff, I know its a pretty large library with lots of settings that all interact with each other. If there's any way I can help, I'd be happy to.

I'll probably open a discord server for stuff like that soon.

**Comment by NarryG** [comment]
Yeah. I set it to include private members since up until now, we used BinaryFormatter which serialized literally everything (and as such, I knew there was nothing we were throwing at it that'd cause too much of a problem) but I agree it's not a good solution.
