### ISSUE TITLE
Problems with inherited properties with initializers?

### ISSUE THREAD

**Issue by microdee** [rikimaru0345/Ceras#25]
So to explain the bad title:
On Ceras 3.0.2 let's say I have these classes:

``` CSharp
public abstract class Person
{
    public List<Person> Friends { get; private set; } = new List<Person>();
}

public class Adult : Person
{
    public byte[] Serialize() => new CerasSerializer().Serialize<object>(this);
}
```

and later on my program modifies the `Friends` list. Unfortunately these don't seem to get serialized. I'm only getting an empty list on deserialization. Maybe this is related https://github.com/rikimaru0345/Ceras/issues/9#issuecomment-450392118 ? So I tried this: (lazily construct the collection)

``` CSharp
public abstract class Person
{
    private List<Person> _friends; 
    public List<Person> Friends
    {
        get => _friends ?? (_friends = new List<Person>());
        private set => _friends = value;
    }
}

public class Adult : Person
{
    public byte[] Serialize() => new CerasSerializer().Serialize<object>(this);
}
```

It works that way, and stuff gets demonstrably serialized. But weird thing is that this works when it's not an inherited property:

``` CSharp
public class Person
{
    public List<Person> Friends { get; private set; } = new List<Person>();

    public byte[] Serialize() => new CerasSerializer().Serialize<object>(this);
}
```

I'd like to conduct further tests but I'm on deadline and I'm fine with this workaround for now.

**Comment by rikimaru0345** [comment]
Hi, I'll take a look at this in detail in the next hours.
But for now there are a few things I can say just at a glance:

1. By default Ceras does only use public fields, nothing else. There are lots and lots of ways to configure that behaviour. The easiest would be to just set `config.DefaultTargets = ...`, or just use the `[MemberConfig]` attribute on your class (or the `[Include]` attribute).
 
2. It could also be a bug. Maybe your code just doesnt show any attributes or that you're actually using a config (bc it looks like you dont). But maybe that is just because you made a smaller example with less clutter.

3. As for the relation to readonly fields: I don't think this is really related, as long as there is any setter at all in your property (even if its `private set;` just like you have) then everything should work perfectly fine.
The readonly field stuff applies only to fields because only they can be readonly. As for properties defined like `public string Bla {get;} = "asdfg";` that's a whole different story  (an entirely different kind of property) and more or less impossible to solve as there really is no setter.  For that you'd be looking into modifying compiler-generated backing fields. But attepting that is getting close to crazy-territory :P (Ceras has some tools to make working with that easier, but I definitely don't reccomend it unless you're an expert haha)


Let me know if the first point already helps, or not. I'll take a deeper look into all of this later.
Keep in mind that you might  run into some trouble if you change the default targets and then Ceras gathers your property AND your custom backing field. (In your case there won't be any problems, but I'm talking about the general case, where your property would so some additional stuff).

**Comment by rikimaru0345** [comment]
As for this example:
```csharp
public class Person
{
    public List<Person> Friends { get; private set; } = new List<Person>();

    public byte[] Serialize() => new CerasSerializer().Serialize<object>(this);
}
```

That won't work either.
The `Friends` list won't be `null` after deserialization, but that is only because when you do `new Person()` a new instance of the list will be created by default.

Try adding a new object to the `Friends` list and serialize it. It will not work. Because Friends is a property.

For the next version of Ceras I will most likely change the default from `all public fields` to `all public fields and properties` to prevent issues like this in the future.

**Comment by rikimaru0345** [comment]
It looks like to me that the mystery is solved and so I guess this issue can be closed.

If not then definitely feel free to reopen the issue or create a new one or whatver! :smile:

**Comment by microdee** [comment]
Thanks for the reply, sorry I had a simplified example where I omitted the config to look more compact, so yeah I'm having properties set for default targets also that's why the second example works for me. I will do further tests at some point regarding this.

**Comment by rikimaru0345** [comment]
Ok so after reading your last comment it definitely sounds like a bug.
That scenario is definitely supposed to work the way you described it.

I've investigated it just now and found the issue.
It doesn't seem hard to fix, so I'll push a fix for that today.

I'm not entirely sure when I'll make a new nuget package however (maybe a week or so?) because I have some cool new features in the pipeline that should be part of the new release. :smile: 

For a workaround in the meantime just make the setter in the base class public as well.
I hope that helps, if not, let me know :+1:

**Comment by microdee** [comment]
oh cool thanks, I'm looking forward to that release ;)
