### ISSUE TITLE
Not serializing types properly

### ISSUE THREAD

**Issue by beeuhtricks** [rikimaru0345/Ceras#29]
The serializer is serializing all of the fields on one of my types to null. I'm sure I'm missing something basic here, but I would love some help debugging this.

**Comment by rikimaru0345** [comment]
Hi :)
Can you post the type definition and how you configure the `SerializerConfig` (if you use that)?

**Comment by rikimaru0345** [comment]
Also, what version are you using, the latest on NuGet? Or did you download the latest commit from github and compile Ceras yourself?

The nuget version is a bit old (~25days) and a lot of improvements were implemented since then.

In the newest version there is a super-easy way to see why exactly some stuff did or did not get included in the serialization.
So if you are using the latest commit, try doing something like this: `config.ConfigType<YourClass>()` to get the TypeConfig, and then inside its `.Members`, each of the `MemberConfigs` has a property named `IncludeExcludeReason`.

Coincidentally I'm actually working on polishing this feature some more right now.


But if you are using the nuget version it's still no problem.
I think, by default, in the old version Ceras only serializes public fields.
You can easily override that by placing a [MemberConfig] on the type and setting the settings in it, or adding [Include] attributes to each member.

**Comment by beeuhtricks** [comment]
Yes, I can. I also just tried it with declaring the serializer as <object> type instead of StoredModel, and it seems to be working properly, which is rather strange.
```csharp
public class StoredModel : ISerializableModel<ModelObject> 
{
        public string Name { get; set; }
        public string Path { get; set; }
        public DateTime Timestamp  { get; set; }
        public MyVersionNumber Version { get; set; }
        public List<ModelObject> Data { get; set; }
        public Dictionary<ModelObject, UserAttributeWrapper> DataWithAttributes { get; set; }
}
```
MyVersionNumber and UserAttributeWrapper are custom types I control, as is ISerializableModel. ModelObject is a third-party type, but I thought Ceras could serialize those as well, and furthermore I assumed that wasn't the issue because the DateTime and string fields were also null. I'm not using any special configuration.

**Comment by beeuhtricks** [comment]
This is using the NuGet package.

**Comment by rikimaru0345** [comment]
`I also just tried it with declaring the serializer as type object instead of StoredModel, and it seems to be working properly, which is rather strange.`
Like `ceras.Serialize<object>(x)` instead of `ceras.Serialize(x)`? If so, that is indeed very strange, the type itself should not have any impact on the "schema" (the description of what members are included in the serialization). That sounds like a bug in Ceras. I'll put it on my todo list to investigate that.

> ModelObject is a third-party type, but I thought Ceras could serialize those as well,
Indeed, Ceras is intended to be able to serialize pretty much anything. Fixing/including anything thats missing should be easy (in theory).

Try this:
```csharp
var config = new SerializerConfig();
config.DefaultTargets = TargetMember.AllPublic;

var ceras = new CerasSerializer(config);
`

**Comment by beeuhtricks** [comment]
> > I also just tried it with declaring the serializer as type object instead of StoredModel, and it seems to be working properly, which is rather strange.
> 
> Like `ceras.Serialize<object>(x)` instead of `ceras.Serialize(x)`? If so, that is indeed very strange, the type itself should not have any impact on the "schema" (the description of what members are included in the serialization). That sounds like a bug in Ceras. I'll put it on my todo list to investigate that.

Correct.

> > ModelObject is a third-party type, but I thought Ceras could serialize those as well,
> 
> Indeed, Ceras is intended to be able to serialize pretty much anything. Fixing/including anything thats missing should be easy (in theory).
> 
> Try this:
> 
> ```cs
> var config = new SerializerConfig();
> config.DefaultTargets = TargetMember.AllPublic;
> 
> var ceras = new CerasSerializer(config);
> ```

Well now...this is interesting:
`Exception: Cannot deserialize type 'System.Collections.Immutable.ImmutableDictionary`2[[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.Double, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]' because it has no parameterless constructor (support for serialization-constructors will be added in the future)
`

UserAttributeWrapper uses ImmutableDictionary internally. I assumed because this was a system type that it would work properly, though I suppose it's only included by default with .NET Core.

Switching that to a regular mutable dictionary seems to work, and now I get a new error about VersionNumber not having a parameterless constructor. My bad for not writing parameterless constructors, I suppose, though perhaps these exceptions should be thrown without the AllPublic setting if they are going to break serialization of the entire type?

Now there's a new exception which I am much less certain of how to fix:
`
  | Name | Value | Type
-- | -- | -- | --
  | StackTrace | "   at System.Reflection.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)\r\n   at Ceras.SimpleTypeBinderHelper.GetTypeFromBase(String baseTypeName) in C:\\projects\\ceras\\src\\Ceras\\Helpers\\NaiveTypeBinder.cs:line 64\r\n   at Ceras.Formatters.TypeFormatter.Deserialize(Byte[] buffer, Int32& offset, Type& type) in C:\\projects\\ceras\\src\\Ceras\\Formatters\\TypeFormatter.cs:line 112\r\n   at Ceras.Formatters.ReferenceFormatter`1.Deserialize(Byte[] buffer, Int32& offset, T& value) in C:\\projects\\ceras\\src\\Ceras\\Formatters\\ReferenceFormatter.cs:line 198\r\n   at lambda_method(Closure , Byte[] , Int32& , StoredModel& )\r\n   at lambda_method(Closure , Byte[] , Int32& , StoredModel& )\r\n   at Ceras.Formatters.ReferenceFormatter`1.Deserialize(Byte[] buffer, Int32& offset, T& value) in C:\\projects\\ceras\\src\\Ceras\\Formatters\\ReferenceFormatter.cs:line 286\r\n   at Ceras.CerasSerializer.Deserialize[T](T& value, Byte[] buffer, Int32& offset, Int32 expectedReadLength) in C:\\projects\\ceras\\src\\Ceras\\CerasSerializer.cs:line 416\r\n   at Ceras.CerasSerializer.Deserialize[T](Byte[] buffer) in C:\\projects\\ceras\\src\\Ceras\\CerasSerializer.cs:line 368\r\n`...

**Comment by rikimaru0345** [comment]
I'll add support for ImmutableDictionary :+1: 

> now I get a new error about VersionNumber not having a parameterless constructor. My bad for not writing parameterless constructors,

There are a few solutions:
- you could have no constructors (then the compiler generates the default parameterless one)
- in the latest version that's about to be released you can do `config.ConfigType<VersionNumber>().ConstructByUninitialized()` if you want to.
- you can add a custom formatter (I wouldn't advise it, it's not worth the effort, but it's an option)
- if you have a ctor that takes a parameter, you can just add a public parameterless one.

> I suppose, though perhaps these exceptions should be thrown without the AllPublic setting if they are going to break serialization of the entire type?

I'm all for improving exceptions, or throwing exceptions earlier if something is wrong with the config (so no time is wasted).
But I don't think I'm entirely sure what you mean.
The targetmember setting determines what members of a type are included, but what if a type is not even encountered (because it's never included through any member)?

> Now there's a new exception which I am much less certain of how to fix:
`Inner Exception 1: ArgumentNullException: Value cannot be null. Parameter name: name`
This appears to be happening when deserializing the dictionary.

What dictionary is that? The generic `Dictionary<K,V>`?
I'm not sure where that happens or what is null. Can you show the full exception? Including the stack-trace, and the "container" exception if it is relevant.

**Comment by beeuhtricks** [comment]
> I'll add support for ImmutableDictionary 👍
Thank you so much!

> > now I get a new error about VersionNumber not having a parameterless constructor. My bad for not writing parameterless constructors,
> 
> There are a few solutions:
> 
> * you could have no constructors (then the compiler generates the default parameterless one)
> * in the latest version that's about to be released you can do `config.ConfigType<VersionNumber>().ConstructByUninitialized()` if you want to.
> * you can add a custom formatter (I wouldn't advise it, it's not worth the effort, but it's an option)
> * if you have a ctor that takes a parameter, you can just add a public parameterless one.
Definitely least effort to just add a parameterless constructor, and for types that need to work with a wide variety of serialization frameworks, it's a good idea anyways. I think this happened because I was switching from Newtonsoft.Json, which I believe falls back to constructors with parameters.

> > I suppose, though perhaps these exceptions should be thrown without the AllPublic setting if they are going to break serialization of the entire type?
> 
> I'm all for improving exceptions, or throwing exceptions earlier if something is wrong with the config (so no time is wasted).
> But I don't think I'm entirely sure what you mean.
> The targetmember setting determines what members of a type are included, but what if a type is not even encountered (because it's never included through any member)?
So if I don't set that setting, no members of the type are included? I guess I was not aware that was how the serializer worked, as it doesn't appear in any of the examples. To be clear, I wasn't getting any exceptions at all without that configuration. The default configuration was just serializing every single field in the type as null, including the ones that normally should have been serialized, unless I told it to serialize and deserialize to object.

> > Now there's a new exception which I am much less certain of how to fix:
> > `Inner Exception 1: ArgumentNullException: Value cannot be null. Parameter name: name`
> > This appears to be happening when deserializing the dictionary.
> 
> What dictionary is that? The generic `Dictionary<K,V>`?
> I'm not sure where that happens or what is null. Can you show the full exception? Including the stack-trace, and the "container" exception if it is relevant.

Here it is: 
```
"   at System.Reflection.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)\r\n   at Ceras.SimpleTypeBinderHelper.GetTypeFromBase(String baseTypeName) in C:\\projects\\ceras\\src\\Ceras\\Helpers\\NaiveTypeBinder.cs:line 64\r\n   at Ceras.Formatters.TypeFormatter.Deserialize(Byte[] buffer, Int32& offset, Type& type) in C:\\projects\\ceras\\src\\Ceras\\Formatters\\TypeFormatter.cs:line 112\r\n   at Ceras.Formatters.ReferenceFormatter`1.Deserialize(Byte[] buffer, Int32& offset, T& value) in C:\\projects\\ceras\\src\\Ceras\\Formatters\\ReferenceFormatter.cs:line 198\r\n   at lambda_method(Closure , Byte[] , Int32& , StoredModel& )\r\n   at lambda_method(Closure , Byte[] , Int32& , StoredModel& )\r\n   at Ceras.Formatters.ReferenceFormatter`1.Deserialize(Byte[] buffer, Int32& offset, T& value) in C:\\projects\\ceras\\src\\Ceras\\Formatters\\ReferenceFormatter.cs:line 286\r\n   at Ceras.CerasSerializer.Deserialize[T](T& value, Byte[] buffer, Int32& offset, Int32 expectedReadLength) in C:\\projects\\ceras\\src\\Ceras\\CerasSerializer.cs:line 416\r\n   at Ceras.CerasSerializer.Deserialize[T](Byte[] buffer) in C:\\projects\\ceras\\src\\Ceras\\CerasSerializer.cs:line 368\r\n
```

This trace has been truncated at the Ceras library callsite because the rest of the information is proprietary.

**Comment by rikimaru0345** [comment]
> ` at System.Reflection.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)\r\n   at Ceras.SimpleTypeBinderHelper.GetTypeFromBase(String baseTypeName)`

Hmm, it looks like the name type name it is trying to resolve is null?
I'm not sure how that can happen :( 
Is there some way I can reproduce that problem? If not, I fear that it's going to be really difficult even figuring out the problem.

Maybe, an alternative could be trying the latest github commit?
There are been some changes regarding the type lookups recently as well.
Not sure if that would actually help though. Just a thought. 

As for the immutable types, the implementation is going well. A lot of code can be reused from ReadonlyCollection! I hope I can release ceras v4.0 tomorrow, maybe even today.

**Comment by rikimaru0345** [comment]
> I think this happened because I was switching from Newtonsoft.Json, which I believe falls back to constructors with parameters.

Hmm, I wasn't aware that Newtonsoft.Json automatically falls back to picking some constructor.
That's actually a good idea.
As I said the new version will have support (or rather, it already has, the feature is done) for serialization constructors. But it won't automatically pick one.
I will take a look at Newtonsoft.Json and see how - according to what rules - it picks the ctor and probably add the same thing to Ceras. :+1:

**Comment by rikimaru0345** [comment]
> So if I don't set that setting, no members of the type are included? I guess I was not aware that was how the serializer worked, as it doesn't appear in any of the examples. To be clear, I wasn't getting any exceptions at all without that configuration. The default configuration was just serializing every single field in the type as null, including the ones that normally should have been serialized, unless I told it to serialize and deserialize to object.

By the default setting for `DefaultTargets` is `PublicFields`, and seeing as your type has no public fields (but public properties) that was the problem.
However, you're not the first one to report that, so for v4.0 the default has already changed to `AllPublic`. Which should be more in line what people expect I think.

If `Serialize<object>()` really makes a difference that would be extremely strange and a huge bug.
I haven't had time yet to investigate it, but if you could create a small sample that shows the problem that'd help me a lot. If not, I'll mess around with it myself for a bit to try to find the issue.

**Comment by rikimaru0345** [comment]
Ah, one more question: 
What platform are you targetting?

net framework v4.5? or 4.7+? or  .net standard 2.0?

**Comment by beeuhtricks** [comment]
> > So if I don't set that setting, no members of the type are included? I guess I was not aware that was how the serializer worked, as it doesn't appear in any of the examples. To be clear, I wasn't getting any exceptions at all without that configuration. The default configuration was just serializing every single field in the type as null, including the ones that normally should have been serialized, unless I told it to serialize and deserialize to object.
> 
> By the default setting for `DefaultTargets` is `PublicFields`, and seeing as your type has no public fields (but public properties) that was the problem.
> However, you're not the first one to report that, so for v4.0 the default has already changed to `AllPublic`. Which should be more in line what people expect I think.

Ahhh, my mental model for public auto-properties is that they are a sugar for public fields with getters and setters. I realize they are internally a private backing field with public accessors. My bad.

> If `Serialize<object>()` really makes a difference that would be extremely strange and a huge bug.
> I haven't had time yet to investigate it, but if you could create a small sample that shows the problem that'd help me a lot. If not, I'll mess around with it myself for a bit to try to find the issue.

Yes, I will try to replicate this.

**Comment by rikimaru0345** [comment]
> Ahhh, my mental model for public auto-properties is that they are a sugar for public fields with getters and setters. I realize they are internally a private backing field with public accessors. My bad.

You are thinking about this is completely right actually, though there are a few small differences that can have a huge impact.

Yes, auto-props are essentially just a getter and setter, which both refer to a **private** field.
So from a serializers point of view (or better: the way the reflection api sees it), there is no public field (only a private one). And theres also a public property (but ceras ignores that by default in the old v3).

Another difference is that those automatically generated private backing fields are explicitly marked with the `[CompilerGenerated]` attribute. Which often indicates some pretty dangerous stuff (well, definitely not in this case, but backing fields of properties are the exception here :P). If you want to know what I mean by that, then issue #11 is probably a really good read :smile: 

Anyway, there are a lot more subtle differences regarding properties, especially with the "new" (well, kinda) syntax like this `public Thing Bla { get; } = new Thing();`, that actually doesn't even have a setter, so it'd count as a "computed property" (which can obviously never get serialized, because there's not even a concept of "setting").

Or the "older"/classical equivalent of a computed property - one that illustrates the point really well - would be this:

`public int Time { get => Environment.TickCount; }` 

Well, that was quite the tangent haha. The only point I was trying to make is that with properties things can sometimes get a bit tricky. Anyway, it never hurts to know I guess.

**Comment by beeuhtricks** [comment]
Yes, I always forget that properties are actually private ;). 

After attempting to replicate that bug with the different type serializers, I think I was mistaking the byte array generated by the object-typed serializer being larger for it actually serializing properly, whereas I now assume it must just be type information and other structural metadata. (they both deserialize to properties to null in my attempt to replicate, basically) I will look deeper into the problem with the dictionary later today. Thank you so much for your help.

**Comment by rikimaru0345** [comment]
> I think I was mistaking the byte array generated by the object-typed serializer being larger for it actually serializing properly, whereas I now assume it must just be type information and other structural metadata.

Ah yes, that would explain it!
The size is indeed expected to be larger when the target-type doesn't match the actual type (so type-information is embedded).

By the way, should that bother you at some point (the type information being embedded), then you can make use of `config.KnownTypes`. Very useful for networking scenarios where you definitely want to avoid sending type-names as strings. The encoding ceras uses for known types (or previously encountered types is as efficient as it can possibly be since that part was made with networking in mind specifically).

**Comment by rikimaru0345** [comment]
Commit https://github.com/rikimaru0345/Ceras/commit/01c1ba241c65537421fcb390c87c8b1d6e84c860 will solve any issues with immutable collections.

It will be available as a nuget package.
I'll publish it together with Ceras v4.0, but that will still take a little longer.
I hope I can get that release out tomorrow.

**Comment by rikimaru0345** [comment]
The preview (release candidate) version 4.0 of Ceras is now available on nuget.
https://www.nuget.org/packages/Ceras/4.0.0-rc

The addon for immutable collections is done as well: https://www.nuget.org/packages/Ceras.ImmutableCollections/

One of the new features in this version is this method:
`ceras.GenerateSerializationDebugReport(type);`
It returns a string that explains in detail how the type will be serialized, what members are included and excluded and most importantly it has reasons for inclusion/exclusion.

Try it and let me know how it goes.

**Comment by beeuhtricks** [comment]
Thank you so much @rikimaru0345

**Comment by thorichelli** [comment]
Hello, the new version 4.0 rc cannot serialize System.Drawing.Color.

This is the exception it throws;

> Expression of type 'System.Drawing.Color' cannot be used for parameter of type 'System.Object' of method 'Void SetValue(System.Object, System.Object)

```
public class MyClass
{
        private System.Drawing.Color backColor;
        public System.Drawing.Color BackColor { get {return backColor;} set{ backColor = value;} }
}
```

**Comment by rikimaru0345** [comment]
@thorichelli 
I've added that problem to my todo list, should be relatively easy :)
But I think this might be better as a new issue.
