### ISSUE TITLE
Bug: Trying to serialize System.Drawing.Color throws exception

### ISSUE THREAD

**Issue by thorichelli** [rikimaru0345/Ceras#31]
If a class has any field with type System.Drawing.Color, CerasSerializer.Serialize throws Exception:

> Expression of type 'System.Drawing.Color' cannot be used for parameter of type 'System.Object' of method 'Void SetValue(System.Object, System.Object)

I am using version 4.0 rc, .Net 4.5, to reproduce the bug, try to serialize the following class with following Config;

```
var sc = new SerializerConfig();
sc.DefaultTargets = TargetMember.AllFields;
sc.VersionTolerance = VersionTolerance.AutomaticEmbedded;

var ceras = new CerasSerializer(sc);
ceras.Serialize(new MyClass());

public class MyClass
{
        private System.Drawing.Color backColor;
        public System.Drawing.Color BackColor { get {return backColor;} set{ backColor = value;} }
}
```

**Comment by rikimaru0345** [comment]
Thanks, this is fixed in https://github.com/rikimaru0345/Ceras/commit/b758ddfa1ccdc7240a07ab23377a7791322260cd

Ceras has a built-in formatter for `System.Drawing.Color` now.

There is still one other small problem remaining regarding version tolerance. I think once that's fixed I'll push a new version to nuget.

**Comment by rikimaru0345** [comment]
The new version is live on nuget now:
https://www.nuget.org/packages/Ceras/4.0.22
