### ISSUE TITLE
Bug: Argument out of bounds exception

### ISSUE THREAD

**Issue by beeuhtricks** [rikimaru0345/Ceras#34]
**Describe the bug**
I'm trying to deserialize the same type I was in issue #29, and it fails with an ArgumentOutOfRangeException.

**How to reproduce the bug**
I'm using the default serializer configuration, and stepping through the debugger what's happening is Ceras is attempting to access an object with id 118 in ObjectCache._deserializationCache (inside the method ObjectCache.GetExistingObject()) and _deserializationCache has a Count of 0.

**Platform**
I'm on .NET Framework 4.7.2, and Ceras version 4.0.27

**Comment by beeuhtricks** [comment]
I discovered the problem. I changed the serializer configuration between serializing and deserializing, which is noted to make previously serialized data possibly incompatible.

**Comment by rikimaru0345** [comment]
Yeah that makes sense.

I was thinking about creating a sort of "config hash" that could be compared for situations like that.

But it wouldn't help with making backwards-compatible changes, since any change would change the hash, no matter if back-compatible or not.
So it's dubious if that idea would even help.

**Comment by beeuhtricks** [comment]
Two thoughts:

1. Do you know what changes are backwards compatible and which aren’t? Is this difficult to parse out of the code? (No pun intended)

2. It might still be useful to have a config hash as a configurable option, you could warn or something if the configs differ. I for one forgot I had changed the config.


________________________________

**Comment by rikimaru0345** [comment]
> It might still be useful to have a config hash as a configurable option, you could warn or something if the configs differ. I for one forgot I had changed the config.

Yeah, adding an option that would allow users to automatically get a config-hash embedded into the data is on my todo list already.
Once that's done there will also be a way to only calculate the hash once at the start and then manually do something with it (for cases where you'd not want automatic embedding, for networking scenarios for example).

> Do you know what changes are backwards compatible and which aren’t? Is this difficult to parse out of the code?

Making a complete list wouldn't be hard, but pretty time consuming since there are so many settings and different combinations of settings.
There are even cases where changes are "partially compatible" as well; for example adding a configuration for a type that has never been serialized yet.´

Then there's also the issue of new features being added and the whole project still evolving a bit (well, since most of the features I want are implemented now it has settled down a bit, but there are still some occasional changes that go a bit deeper).

If you have a question about any specific feature or set of features let me know and I'll answer about their backwards-compatibility in detail.
