### ISSUE TITLE
Bug: Error when serializing structs

### ISSUE THREAD

**Issue by oruchreis** [rikimaru0345/Ceras#40]
We are getting "Index was outside the bounds of the array" exception when serializing structs. I've tried many versions, also latest 4.0.36.
You can reproduce this with this code:
```
#r "nuget:Ceras/4.0.36"

using Ceras;

public struct Price
{
    public decimal Value { get; set; }
    public string Curreny { get; set; }
}
CerasBufferPool.Pool = new CerasDefaultBufferPool();
var p = new Price{ Value = 1.2m, Curreny = "TRY"};

var serializer = new Ceras.CerasSerializer(new SerializerConfig { PreserveReferences = true });

var s = serializer.Serialize(p);
```
Here is the stacktrace :
```
   at Ceras.SerializerBinary.FastCopy(Byte[] sourceArray, Int32 sourceOffset, Byte[] targetArray, Int32 targetOffset, Int32 n) in C:\projects\ceras\src\Ceras\SerializerBinary.cs:line 462
   at Ceras.CerasSerializer.Serialize[T](T obj) in C:\projects\ceras\src\Ceras\CerasSerializer.cs:line 359
   at async Program.<Initialize>(?) in :line 15
   at Program.<Main>()
```
If I try with 4.0.26 version it can't serialize and returns zero byte array. Also If I convert "Price" struct to a class, it can serialize and deserialize successfully.

**Comment by rikimaru0345** [comment]
Thanks for reporting, I'll take a look!

**Comment by rikimaru0345** [comment]
First investigation shows a few things:
- The members of the struct are simply not included. That's why nothing is serialized. This is probably a bug and I'll check it out in more detail later...
The reason given is this: `Excluded: Member is 'PublicProperty', which is excluded through the configuration 'AllFields' of the declared Type 'Price'`

By the way, you can get this information by calling: `ceras.GenerateSerializationDebugReport(typeof(Price));`


- Next there is a small issue when the result of a serialization is 0 bytes (which should not really happen anyway, unless of course your target-type is completely empty, which is the edge-case we're dealing with here). I'll fix that.

**Comment by rikimaru0345** [comment]
Ah, you can fix this yourself already by doing one of those things:

- Add [Include] to the props

- Add a [MemberConfig] to your struct and set its settings

- Do what the attributes above would do manually with: `
			config.ConfigType<Price>().SetTargetMembers(TargetMember.AllPublic);`

Also just a few hints: You are using PreserveReferences=true (the default is true already btw), and it doesn't seem like you'd need it. And since it has a small performance impact I'd suggest turning it off.
If you do that, Ceras will do what other serializers like msgpack, protobuf, json, ... do; which is just following all references and serializing them, ignoring the fact hat two objects might be the same. That's not really correct but it is how most serializers work and it gives you a performance boost.

The only case when you want to leave this enabled is when you have circular references (object a<->b referencing each other) or "shared-references" (objects A and B both referencing C).

**Comment by oruchreis** [comment]
I can't add attributes or change the type of the struct. I sent here price as an example, but we have lots of auto-generated structs and classes. I have written an IFormatter for the price struct but it takes lots of time to implement other formatters for other structs.

**Comment by rikimaru0345** [comment]
@oruchreis It's fixed now! :smile: 

But should you encounter an issue like that again, you could (as a workaround I mean) just change the configuration of the type. No need to modify the structs or classes themselves with attributes.

Check out the non-generic `ConfigType()` method (many examples in the unit tests in Ceras), and the `OnConfigNewType` of the `SerializerConfig`.
That way you can procedurally configure all your types. :+1: 

Let me know if there are any other problems.
The CI build will be started soon, so it shouldn't take much longer than 20 or so minutes for the update to appear on nuget as well.
