### ISSUE TITLE
support Exception serialize/deserialize?

### ISSUE THREAD

**Issue by fredliex** [rikimaru0345/Ceras#42]
I want serialize/deserialize Exception and derived types.
The initial idea is implement ExceptionFormatter, like below.
```
public sealed class ExceptionFormatter<T> : IFormatter<T> where T : Exception {
   public void Serialize(ref byte[] buffer, ref int offset, T value) {
      var binaryFormatter = new BinaryFormatter();
      ... append byte[] generated by binaryFormatter to the buffer...
   }
   public void Deserialize(byte[] buffer, ref int offset, ref T value) {
      var binaryFormatter = new BinaryFormatter();
      ... use the binaryFormatter to read the buffer to deserialize value...
   }
}
```

`BinaryFormatter` seems too fat.
Did I miss the reference Exception?
Any suggestions?

thanks.

**Comment by rikimaru0345** [comment]
Should be no problem to make this work somehow.

What *exactly* are you looking for though?

Are you looking for a "specialized" serialization that only includes stuff you care about?
I suppose you obviously want the actual Type of the exception and its Message, and the InnerException is also essential...
But what about other things? StackTrace is very important in most scenarios, so that should be included, right? But maybe you don't need that?

Or are you simply looking for a perfect copy? That should be totally doable as well...

Did you try just giving the exception instance directly to Ceras? Are there some problems with doing that? Personally I have not yet tried to serialize exceptions, so I'm not sure if it works.

But even if there are some issues, I'm certain they can be fixed more or less easily :)


Let me know what you think.
I will have more time in a few hours; then I'll try to serialize some exceptions and see what happens.

**Comment by fredliex** [comment]
I am looking for something to replace my WCF.
This includes some serializer instead of DataContractSerializer.
DataContractSerializer is nice but not friendly.

For exception, I hope serializer can keep detailed information so that the caller can re-throw the exception, so there must has Type and a Message.
It would be better if it could include StackTrace and InnerException, which can help developers.

It would be better if Ceras could build support for exceptions.
But if the inside is implemented with BinaryFormatter, I think it will affect the cleanliness of Ceras.
But at the moment I can't think of a way to practice without using BinaryFormatter.

What do you think?

**Comment by fredliex** [comment]
I have considered it too much.
Very simple to solve with the following.
`new CerasSerializer(new SerializerConfig { DefaultTargets = TargetMember.All })`

Sorry for disturbing you. 😄

**Comment by rikimaru0345** [comment]
Good that it works for you.
If there is something still missing or not working, be sure to let me know :D
