### ISSUE TITLE
how reuse CerasSerializer to Improve performance?

### ISSUE THREAD

**Issue by fredliex** [rikimaru0345/Ceras#43]
I know that CerasSerializer is not thread safe.
If I apply to SOA, every request is made to create a Serializer, I feel that there is a lot of performance waste.
How can I avoid doing duplicate things every request?
For example, dynamically generate Lambda for `DynamicFormatter<T>`, get specific IFormatter<T> from `CerasSerializer.GetFormatter<T>`, etc...

Is it possible to reuse the same CreasSerializer instance?
Use lock?.....I feel worse...
Use pool?.....

Any suggestions?

**Comment by rikimaru0345** [comment]
Yes, creating a new CerasSerializer instance is a **very** expensive operation.
Ceras is designed so Serialize/Deserialize are fast as possible, so as much as possible is moved to initialization time.

In a server application where you have to respond to multiple requests in parallel, should create a pool of serializers.

In the simplest case you can just have a `Stack<CerasSerializer>` where you take out a serializer when you need one, and return it once you're done. Just remember to lock the collection while Pushing/Popping into/out of the collection.

You probably won't even need a much more complicated setup for pooling.

To further improve performance remember to not use the "beginner version" of Serialize (where it returns an array for you). Instead use the `Serialize<T>(T obj, ref byte[] buffer, int offset = 0)`. It returns the amount of bytes written to the buffer. That way you can reuse/recycle the buffer and Ceras does not have to create a new byte array for you each time.

**Comment by fredliex** [comment]
Ok. I know what you mean.
I will try it.

thanks.  😄

**Comment by rikimaru0345** [comment]
> Ok. I know what you mean.
> I will try it.
> 
> Of course, if possible, I hope I can reuse singleton instance.
> 
> thanks.

A singleton is possible if you manually `lock()` the instance. But for a server application I would not recommend it because you'd introduce a single bottleneck though which all requests have to go.

If you are concerned about memory consumption you can try limiting your pool to the number of CPU cores. That's actually a good idea in any case because using more threads than cores rarely scales well.

That way you really get the theoretical maximum performance with the way the project is currently structured.
