### ISSUE TITLE
Comparison with Odin serializer?

### ISSUE THREAD

**Issue by asusralis** [rikimaru0345/Ceras#57]
Hello! Firstly, thanks so much for Ceras; it has been much easier to use than other serializers for us. I was curious on its comparison with Odin serializer? We already use that for serializing for editing data in Unity, but we use Ceras for our network serialization. I was curious if you had any input between the two!

https://github.com/TeamSirenix/odin-serializer

**Comment by rikimaru0345** [comment]
Hey, glad Ceras works well for you! :) 

I don't really know much about Odin unfortunately, but it seems to have a similar (?) feature set.

At the moment I don't have much time to do a detailed comparison, but maybe (since you already know both serializers) have some input?
I mean, if you can mention some topics you're interested in specifically, I could offer my opinion on those things in particular (after investigating how odin handles those) :P 

Looking at the comparison table in their repo the only thing that Ceras doesn't do is `Json Formatter`. 
That requires embedding the type of each member (field, prop, list/array entry, generic, boxed object, ...).

Maybe that is the biggest difference?

By default Ceras tries to avoid having to embed this type of information if at all possible.

There is a mode (version tolerant mode) where this kind of information is embedded as well. In fact, I think it actually wouldn't be too hard to add a "json output" to data that was saved in version-tolerant mode!

The fact that Ceras tries to avoid having to embed any additional information gives it a few advantages and disadvantages compared to Odin (and the MsgPack format). For example Ceras can be faster because there's simply less data to read/write!

I'm not too sure about long-term storage (saving binary data to files), like how Odin handles changing classes, but I guess it has some sort of mechanism to deal with that as well (seeing as Odins driving idea was making a serialization lib for the unity **editor** initially). 


As for speed... I really don't know. I never compared Odin and Ceras, but I'd be surprised is Odin is much faster (but it's possible, who knows :P) as I always used MessagePack as a benchmark until now.


Next: Serializing/editting data in Unity. Hmm I'm not too sure if Ceras can beat Odin there as it (most likely) has some sort of intermediate representation just like Newtonsoft.Json. I'm talking about classes like `JObject`, `JToken`, ...   and Odin probably has something similar to that  as well; while Ceras does not. I considered having something like that initially but strongly decided against it because it would cost too much performance. And competing at the very top of the performance ladder was (and still is) one of the primary goals of Ceras (along with ease of use, and a broad set of scenarios it can be used in).



How have your experiences been with the two serializers? Anything you noticed that Ceras does a lot worse? Or maybe much better?

**Comment by asusralis** [comment]
Wow, what a detailed response! This pretty much answered my questions. I sadly don't have too much experience with Odin outside of Unity. I would assume most who use it are using it to serialize things in Unity bundled with their inspector library. 

I like Ceras for the simple fact that the team is so small (is it only you?) and you don't have to litter your code with attributes! Do you have plans in the future to get a logo for Ceras? It would be a great thing to be able to add to a project! 

Thanks again!

**Comment by rikimaru0345** [comment]
> I like Ceras for the simple fact that the team is so small (is it only you?) and 

 Do you have plans in the future to get a logo for Ceras? It would be a great thing to be able to add to a project!

Yeah its just me.

> you don't have to litter your code with attributes!

Ah yes, avoiding attributes is important so the library can be swapped in/out quickly. Though there are attributes to configure stuff, for people who like attributes more. But everything they do (and much more even) can be configured by code.

> Do you have plans in the future to get a logo for Ceras? It would be a great thing to be able to add to a project!

No plans yet. 
If the project grows some more once I release v5 (when I finally get around to actually implementing all the remaining features I want haha) I might find someone to make a nice one :)
