### ISSUE TITLE
HOWTO: Deserialize with Type parameter

### ISSUE THREAD

**Issue by AshIceLoky** [rikimaru0345/Ceras#58]
Hi,
I need to do this:
object Deserialize(Type type, Stream source);
I try a lot of way but I don't find a solution.

A sample, from your sample:

`    class TestCeras
    {

        class Person { public string Name; public int Age; }
        static void Main(string[] args)
        {
            var p = new Person { Name = "riki", Age = 5 };
            var ceras = new CerasSerializer();
            var bytes = ceras.Serialize(p);

            Person res = (Person) Deserialize(typeof(Person), new MemoryStream(bytes));
        }

        private static object Deserialize(Type type, Stream source)
        {
            var ceras = new CerasSerializer();
            //var res = ceras.Deserialize<type>(source);
            return res;
        }

    }`

**Comment by rikimaru0345** [comment]
This is from the network example right?

In that specific example I always force serialization as `object`, so Ceras embeds the type data into the bytes. 
In other serializers that would add some considerable overhead, but with Ceras there are many options to avoid this. For example KnownTypes. 

I already took the time to write down pretty much everything (and more) there is to know about KnownTypes, networking and so on. 

See here:
https://github.com/rikimaru0345/Ceras/wiki/Type-Encoding


In the network example you can never know what the other side will send you next, so you can never know the type. That's why it serializes as object. `ceras.Serialize<object>(yourObjectInstance);`
And then on the receiving side you can just do this: `object res = ceras.Deserialize<object>(incomingData);`

After that you can dispatch it to whatever handler you want. For example:

```csharp
object res = ceras.Deserialize<object>(incomingData);

Console.WriteLine("Received Type: " + res.GetType().FullName);

if(res is Person p) 
    HandlePerson(p);

...
```


Does that answer your question?

**Comment by AshIceLoky** [comment]
I have to implement for an external library this interface:
object Deserialize (Type type, Stream source);
I was thinking of replacing the JSon serializer with Ceras, but I can not find a way to do it, even with "KnownTypes"

`
    class TestCeras
    {

        class Person { public string Name; public int Age; }
        static void Main(string[] args)
        {
            var p = new Person { Name = "riki", Age = 5 };

            SerializerConfig config = new SerializerConfig();
            config.KnownTypes.Add(typeof(Person));
            var ceras = new CerasSerializer(config);
            var bytes = ceras.Serialize(p);

            Person res = (Person) Deserialize(typeof(Person), new MemoryStream(bytes));
        }

        private static object Deserialize(Type type, Stream source)
        {
            SerializerConfig config = new SerializerConfig();
            config.KnownTypes.Add(typeof(Person));
            var ceras = new CerasSerializer(config);
            var res = Activator.CreateInstance(type);

            //var res =  type.GetConstructor(new Type[] { }).Invoke(new object[] { });
            //dynamic res2 = Convert.ChangeType(res, type);

            using (MemoryStream ms = new MemoryStream())
            {
                source.CopyTo(ms);
                var tab = ms.ToArray();
                ceras.Deserialize(ref res, tab);
            }
            return res;
        }

    }
`

**Comment by rikimaru0345** [comment]
Ah, I see. 
The type parameter is not really needed because Ceras already embeds the Type into the binary data.

you would just use 
```
object obj = null; // dont use var, don't omit <object>, ...
ceras.Deserialize<object>(ref obj, tab);
return obj;
```

Your serialize code must be adapted that way too then, instead of:
`var bytes = ceras.Serialize(p);`
you must write:
`var bytes = ceras.Serialize<object>(p); // use <object>, don't let the compiler figure out the type implicitly because it will use the direct type, not object` 

that way the serialization format will be forced to contain the type.

That should work without any problems for you.
