### ISSUE TITLE
Any way to serialize getter only properties?

### ISSUE THREAD

**Issue by dbolin** [rikimaru0345/Ceras#63]
I would have expected the following config to work with them
```csharp
var config = new SerializerConfig { DefaultTargets = TargetMember.AllFields, PreserveReferences = false };
config.Advanced.ReadonlyFieldHandling = ReadonlyFieldHandling.ForcedOverwrite;
config.Advanced.SkipCompilerGeneratedFields = false;
```
Targets are all fields, readonly is set to always overwrite, and skip compiler generated fields is also set to false - however, when calling Serialize I get the following exception:
System.InvalidOperationException: 'Sequence contains no matching element'

The class I'm trying to serialize just has a few properties (no set method on the properties, since the class is immutable) of simple types.

**Comment by rikimaru0345** [comment]
Can you show how exactly you are defining your immutable class?

Also, only fields can be force-overwritten, but props without a setter can not.

Keep in mind there is a big difference between a prop with a private setter and one that doesn't have a setter at all. (and what the different c# Syntax features generate).


Can you explain what you are trying to achieve? Maybe I can help.

At least with get-only props you will not be able to Deserialize the class easily. 

An option would be to have {get private set;} 

Or another option would be to create the backing fields manually and assign them in the ctor (ceras can use constructors, it will even auto map them if the names match!)

**Comment by dbolin** [comment]
```csharp
    public sealed class CustomProperty
    {
        public CustomProperty(string key, decimal value)
        {
            Key = key;
            Value = value;
        }

        public string Key { get; }
        public decimal Value { get; }
    }
```

I was trying to compare Ceras performance against what I am currently using for this.

Private setters are not an option - that would defeat the purpose of immutable models and in this case wouldn't even compile.

I'm not going to do manual backing fields because that would be a lot of work and make the type definitions just messier than they should be.

**Comment by rikimaru0345** [comment]
Hey, no problem :) Ceras should be able to deal with this type.
There are multiple things that can be done:

First thing to try is: `ceras.GenerateSerializationDebugReport(type)`.
https://github.com/rikimaru0345/Ceras/blob/master/src/Ceras/CerasSerializer.cs#L1157

It will tell you why exactly some things are excluded.
Maybe its as simple as including fields (using the MemberConfigAttribute or TypeConfig<>() if you prefer code).

That would be serializing the backing fields.
But then again, those are compiler generated and I'd recommend against serializing them (even if it solves the problem).


Next thing to think about is letting Ceras use the constructor.
Take a look at the example here where I select a `ConstructorInfo` from a lambda.

https://github.com/rikimaru0345/Ceras/blob/f8d4db31a33397ba5c9d3f24189e59ce363e5580/tests/Ceras.Test/Tests/ConstructionAndPooling.cs#L26-L28

It will try to map the parameters to the members automatically.
If that fails, you can use:
https://github.com/rikimaru0345/Ceras/blob/master/src/Ceras/Config/TypeConfig.cs#L372


Actually, I realize now that there could (should) be some mode like "ConstructByAutomaticCtor" or something like that. Because having to select the ctor with a lambda isn't all that comfortable (definitely much more comfortable than having to use reflection to find it, but still not perfect).

In your case that'd be ideal. There's just one ctor, and the parameters can be mapped automatically. I just need to find time to add that :P 

Let me know if that helps.

**Comment by rikimaru0345** [comment]
Ah, also 
> I was trying to compare Ceras performance against what I am currently using for this.

Definitely make sure to turn off `config.PreserveReferences` then (Assuming you don't need it for simple models like that one).

and there's also a quick checklist for performance stuff here:
 https://github.com/rikimaru0345/Ceras/wiki/Optimization-&-Pitfalls

**Comment by dbolin** [comment]
Well, we actually have around 100 types like this, so anything that would involve adding some kind of mapping for each type isn't ideal, especially as it would have to be updated whenever a constructor changed.

In some cases the constructor does not match the fields/properties exactly as well, e.g. some types have privately mutable fields for caching computations, or need to enforce certain invariants.  Basically this just means that some types can't be deserialized using a constructor.

**Comment by rikimaru0345** [comment]
Yes that's true, ctor mapping won't help then, even if its automatic. 

Did you try the report method? What does it say about the compiler generated backing fields?

Serializing the backing fields will be the solution for you then I guess, so let's try to figure out why they're not included :)

**Comment by dbolin** [comment]
I get the same error as above when calling GenerateSerializationDebugReport.   I do also have ConstructByUninitialized set for the type.

**Comment by rikimaru0345** [comment]
Ah I see, I'll take a look right now! 😄 

Are you using using the dll from NuGet or are you compiling Ceras yourself from the master branch? It is possible that the master branch is a bit ahead of the NuGet release.

**Comment by rikimaru0345** [comment]
Also, there's another way (that is likely closer to what you tried) to accomplish the exact same thing:

```csharp

var config = new SerializerConfig();

config.Advanced.ReadonlyFieldHandling = ReadonlyFieldHandling.ForcedOverwrite;
config.Advanced.SkipCompilerGeneratedFields = false;
config.DefaultTargets = TargetMember.PrivateFields;

// Next two lines do exactly the same
config.ConfigType(typeof(CustomProperty)).TypeConstruction = TypeConstruction.ByUninitialized();
config.ConfigType<CustomProperty>().ConstructByUninitialized();

			
var ceras = new CerasSerializer(config);

var obj = new CustomProperty("abc", 123.456M);

var report = ceras.GenerateSerializationDebugReport(typeof(CustomProperty));

var data = ceras.Serialize(obj);
var clone = ceras.Deserialize<CustomProperty>(data);

```

**Comment by rikimaru0345** [comment]
AppVeyor build is done, push to nuget will happen in the next minutes as well...

I included both variants of those two lines above because for your case you probably prefer using some approach where you can filter/specify the type dynamically (so generic `config.ConfigType<CustomProperty>()` won't work to configure hundreds of types)

**Comment by dbolin** [comment]
Thanks.  That works.
