### ISSUE TITLE
Dictionary within objet[] within Dictionary within Dictionary causing exception

### ISSUE THREAD

**Issue by SirJosh3917** [rikimaru0345/Ceras#7]
```cs
class Program
{
	static void Main(string[] args)
	{
		var data = new Dictionary<string, object>
		{
			["test"] = new Dictionary<string, object>
			{
				["test"] = new object[]
				{
					new Dictionary<string, object>
					{
						["test"] = 3
					}
				}
			}
		};

		var s = new CerasSerializer();

		//  throws here
		s.Deserialize<Dictionary<string, object>>(s.Serialize(data));
	}
}
```
`System.Exception: 'Cannot deserialize type 'System.String' because it has no parameterless constructor (support for serialization-constructors will be added in the future)'`

**Comment by rikimaru0345** [comment]
Nice find! I fixed it.

What the actual issue was:
When serializing the type-definitions of composite types (closed generics), the inner types got their own reference proxy provided by the composite, instead of them creating their own reference proxy; which in turn made it so nested types got deserialized twice.

Once by the code that's reading the inner definitions of the composite,
and once each by the code that's actually deserializing the inner type.


Fixed in https://github.com/rikimaru0345/Ceras/commit/895d9fcb92bc9d082f0b7954eaa6f7500d7c0f24
