### ISSUE TITLE
Map parameter to member with Attributes for getter-only properties

### ISSUE THREAD

**Issue by MineCake147E** [rikimaru0345/Ceras#74]
I found that there are a lot of things I have to do with a get-only property, like this:
```csharp
using System;
using System.Collections.Generic;
using System.Text;
using Ceras;
using Ceras.Formatters;
namespace CerasWriteTest
{
    [MemberConfig(TargetMember.All, ReadonlyFieldHandling.ForcedOverwrite)]
    public sealed class Entry
    {
        [CerasConstructor]
        public Entry(string a, string b)
        {
            A = a ?? throw new ArgumentNullException(nameof(a));
            B = b ?? throw new ArgumentNullException(nameof(b));
        }
        [field: Include]
        public string A { get; }
        [field: Include]
        public string B { get; }
    }
}
```
```csharp
using System;
using System.Collections.Generic;
using System.Linq;
using Ceras;

namespace CerasWriteTest
{
    internal class Program
    {
        private static void Main(string[] args)
        {
            var config = new SerializerConfig();

            config.Advanced.ReadonlyFieldHandling = ReadonlyFieldHandling.ForcedOverwrite;
            config.Advanced.SkipCompilerGeneratedFields = false;
            config.DefaultTargets = TargetMember.PrivateFields;
            config.ConfigType<Entry>().ConstructByUninitialized();
            var serializer = new CerasSerializer(config);
            Console.WriteLine(serializer.GenerateSerializationDebugReport(typeof(Entry)));
            var bytes = serializer.Serialize(new Entry("test1", "test2"));
            for (int i = 0; i < bytes.Length; i++)
            {
                Console.Write($"0x{bytes[i]:X2}, ");
                if (i % 16 == 15) Console.WriteLine();
            }
            var g = serializer.Deserialize<Entry>(bytes);
            Console.WriteLine($"A:{g.A}, B:{g.B}");
            Console.ReadLine();
        }
    }
}
```
### Solution idea
Add some parameter mappings to `CerasConstructorAttribute` that allows the usage like:
```csharp
using System;
using System.Collections.Generic;
using System.Text;
using Ceras;
using Ceras.Formatters;
namespace CerasWriteTest
{
    public sealed class Entry
    {
        [CerasConstructor(nameof(A), nameof(B))]
        public Entry(string a, string b)
        {
            A = a ?? throw new ArgumentNullException(nameof(a));
            B = b ?? throw new ArgumentNullException(nameof(b));
        }
        public string A { get; }
        public string B { get; }
    }
}
```
and
```csharp
using System;
using System.Collections.Generic;
using System.Linq;
using Ceras;

namespace CerasWriteTest
{
    internal class Program
    {
        private static void Main(string[] args)
        {
            var serializer = new CerasSerializer();
            Console.WriteLine(serializer.GenerateSerializationDebugReport(typeof(Entry)));
            var bytes = serializer.Serialize(new Entry("test1", "test2"));
            for (int i = 0; i < bytes.Length; i++)
            {
                Console.Write($"0x{bytes[i]:X2}, ");
                if (i % 16 == 15) Console.WriteLine();
            }
            var g = serializer.Deserialize<Entry>(bytes);
            Console.WriteLine($"A:{g.A}, B:{g.B}");
            Console.ReadLine();
        }
    }
}
```
I want not to configure more using `SerializerConfig` inconveniently per serializer basis.

**Comment by rikimaru0345** [comment]
I like the idea.
Usage should definitely be as simple and easy to use as possible.

### The actual issue here

The real issue here are the get-only properties.
They make everything a lot more complicated.

The short explanation of why get-only-props make things so troublesome is: their field names are very volatile, so initially (in earlier versions) they weren't supposed to be serialized.

The field names being not really predictable is an issue for version tolerance; but I suppose you don't care about that (right?).

Now we have tons of ways to tell Ceras how to construct an object; from uninitialized, to static- and instance-factory methods, to the use of constructors; so I guess there are still some rough edges in the API when dealing with get-only-props. 


### Some comments on your first and second code block
- Initially the MemberConfig attribute is not needed because...
- ... you don't need to specify `ReadonlyFieldHandling.ForcedOverwrite`  because you're using the constructor attribute. ReadonlyFieldHandling is only needed when the fields are set directly (using an empty ctor, or uninitialized object).
- `TargetMember.All` is not needed because you're using `[Include]` attributes. Only one of them is needed (attributes on members will override member config anyway).

But then `config.ConfigType<Entry>().ConstructByUninitialized();` will override the `[CerasConstructor]` attribute and thus require; thus putting Ceras back into "serialize field by field, use readonly handling".
So you've got a bit of a mix going on there. And in the end the ctor will not get used at all.

But I guess you just ended up with all of that because you've been experimenting with the settings to see what works (right?).

The combination that would take the least amount of attributes would be: `[CerasConstructor]` and `[MemberConfig(TargetMember.All)]`. That way you can avoid the `[field:Include]`
And then you could remove this line: `config.ConfigType<Entry>().ConstructByUninitialized();`

Both approaches, the "constructor" way, and the "forced" way have their advantages and disadvantages.
In your case using a constructor is faster, because that doesn't need any handling to deal with readonly fields (from your get-only props).

But (at least right now unfortunately) it is a bit more complex to use.


### Here's what I think should be changed

1. In your case you need the `[CerasConstructor]` attribute. But I think that should be automatic. in your case the automatic parameter-to-member mapping already works. So the last little step (also automatically inferring the ctor) should be done too! That would allow you to drop the attribute.

2. Your idea to extend the ctor attribute is great. If I understood it correctly `[CerasConstructor(nameof(A), nameof(B))]` would just list the members that the ctor populates in the correct order. Should be pretty straightforward to implement as well.


### About compiler generated fields

This line is bothering me a lot: `config.Advanced.SkipCompilerGeneratedFields = false;`
Unfortunately it is neccesary right now, because otherwise Ceras would not be able to even "see" the backing-fields.
That is on purpose to avoid all sorts of potentially terrible side-effects (serializing state-machines, cached lambdas/delegates, all sorts of stuff when using `dynamic`, ...)

I'm not sure whether or not it is worth it to set it to true by default. There are a lot of things that could go wrong.

Maybe there could be a way to somehow enable support for get-only-props on a per-class basis? Maybe an attribute like `[AllowGetOnlyProps]` or something?
All potential solutions I can think of right now are really bad :( 

What do you think?

**Comment by MineCake147E** [comment]
> Some comments on your first and second code block  

So, should I write the code below for now?:
```csharp
using System;
using System.Collections.Generic;
using System.Text;
using Ceras;
using Ceras.Formatters;
namespace CerasWriteTest
{
    [MemberConfig(TargetMember.All)]
    public sealed class Entry
    {
        [CerasConstructor]
        public Entry(string a, string b)
        {
            A = a ?? throw new ArgumentNullException(nameof(a));
            B = b ?? throw new ArgumentNullException(nameof(b));
        }
        public string A { get; }
        public string B { get; }
    }
}
```
```csharp
using System;
using System.Collections.Generic;
using System.Linq;
using Ceras;

namespace CerasWriteTest
{
    internal class Program
    {
        private static void Main(string[] args)
        {
            var config = new SerializerConfig();
            config.Advanced.SkipCompilerGeneratedFields = false;
            var serializer = new CerasSerializer(config);
            Console.WriteLine(serializer.GenerateSerializationDebugReport(typeof(Entry)));
            var bytes = serializer.Serialize(new Entry("test1", "test2"));
            for (int i = 0; i < bytes.Length; i++)
            {
                Console.Write($"0x{bytes[i]:X2}, ");
                if (i % 16 == 15) Console.WriteLine();
            }
            var g = serializer.Deserialize<Entry>(bytes);
            Console.WriteLine($"A:{g.A}, B:{g.B}");
            Console.ReadLine();
        }
    }
}
```
> Both approaches, the "constructor" way, and the "forced" way have their advantages and disadvantages.
In your case using a constructor is faster, because that doesn't need any handling to deal with readonly fields (from your get-only props).

I thought that the serializer should serialize all properties that are (correctly) mapped with `CerasConstructorAttribute`, just by getting value of property directly... if the getter gets inlined... right?


Can I ask you something more basic...
Why do we need not just to `get` the value from `A { get; }` but to access the backing compiler-generated field?
Please forgive me without enough knowledge about reflection...

**Comment by rikimaru0345** [comment]
That should work, yeah. :)

> I thought that the serializer should serialize all properties that are (correctly) mapped with CerasConstructorAttribute, just by getting value of property directly... if the getter gets inlined... right?

The idea is that object/data persistence comes first.
Think of it that way: the first thing you'd probably want in a serializer is that it persists the data of the object you give it. The question about how it gets re-constructed again at deserialization time is something that comes later.

That means Ceras first wants to know what members (props, and or fields) it should consider a part of the object. Selecting a construction method, mapping serialized values to parameters comes after that, not before.
The "uninitialized" mode is the best example for that.
In that case **no** constructor is used **at all** (not even any default one!).

> Why do we need not just to get the value from A { get; } but to access the backing compiler-generated field?

It would certainly be possible to do it that way :)
However Ceras doesn't really consider the property `A` as a potential member for serialization at all. Because in reality all it is, is a function that returns the value of a backing field. 
Properties aren't even data, fields are.


I hope I can make all of this much much easier to use with the upcoming changes.
When they're done, Ceras should automatically detect that there is a constructor it can use to re-construct the object completely; make use of it; and adapt what members it includes by default as well (accepting get-only props, since it now knows that it can actually write them again, without having to rely on very slow, brute-force methods like `SetValue`)


I hope that makes sense. Let me know if there are any more questions! 😄

**Comment by MineCake147E** [comment]
Thank you for your quick response.
For this situation that I can (legally) **modify** the **class** directly, I forgot that I can add a manual backing field and an expression-bodied getter-only property.
How about a `readonly struct` which can't even have any writable field?
I have no idea because I have no access to my PC right now.
🤔

**Comment by rikimaru0345** [comment]
> For the class/structs that I have no direct write access to them(e.g. types from external libraries), how can I handle them?

If they have a ctor that would work for you, us that in some way. 
With the usual TypeConfig you can control everything.

In fact, attributes are not needed for anything, other than making code more self-describing; everything attributes can do, can also be done using TypeConfig (and a lot more!).

TypeConfig allows you to do all sorts of things for any type. All of Ceras' configuration is made with "external" types in mind.

If we assume that some type you want to serialize has no constructor. then just use `.ConstructByUninitialized();` for construction, and control what members you want to serialize the usual way (either using default targets of the whole type, or control member by member...)

**Comment by MineCake147E** [comment]
Sorry for my late reply…
I understand the correct usage of **current** Ceras you told. Thank you for your straightforward detailed explanation.
I can now fix any issues about getter-only properties by directly modifying them to use manual backing field.
Please close this Issue if we have no issues remaining.
