### ISSUE TITLE
Using PersistTypeCache in a more flexible way.

### ISSUE THREAD

**Issue by asusralis** [rikimaru0345/Ceras#88]
If I understand correctly, PersistTypeCache will serialize type names once and then afterwards use their generated ids afterwards. In a network setting this works well with one client that stays connected but falls apart once you have multiple clients that have the possibility of disconnecting. The first client will understand the ids, but any client afterwards will not! This makes using PersistTypeCache very hard to use, especially in a more general way that can't make use of KnownTypes, which is a shame because of how useful it is in a network setting.

A straightforward way to solve this, I think, would to keep a type cache (or just info on what client has been sent that type before, pointing to the id) for each individual client. You would pass in the client's id during serialization/deserialization so the serializer would know what types have been sent to a specific client. You would then have a method that could manually clear type cache for a specific client. This would be called when a client disconnects.

I took a look at the project wanting to implement something like this but found the type caching wasn't as straightfoward as I thought. It seems it's stored in InstanceData which changes every time Ceras does something? I know you're too busy for this project at the moment, but if you could offer any feedback on this idea or suggestions on implementing it I would be so grateful!

**Comment by asusralis** [comment]
I guess I could also just have a serializer for each client and create a new one when they d/c?

**Comment by rikimaru0345** [comment]
> I guess I could also just have a serializer for each client and create a new one when they d/c?
Yes, that is exactly what I intended people to do anyway. 😄 

Even if one would implement some kind of approach where the server sends a "dictionary" to a newly connecting client; it is not guaranteed that this kind of dictionary is even optimal for that client. Maybe this client will send/receive different objects, so the type cache that was created for the first client doesn't even help that much.
(Sure, for a game that scenario is pretty unlikely; you can probably assume that 90%+ of the send/received types will be the same, but making assumptions like that is a trade off that will likely impact other usage scenarios in a negative way...)

Anyway, if your network handling is multi-threaded / using async-await (which it should! 😄), that is another big reason to do this (using a separate serializer instance for each client) since a `CerasSerializer` instance is not thread-safe (on purpose: no threading checks = better performance).


Also, one more thing to keep in mind is the intended use cases for `PersistTypeCache`:
- Serializing to a file: larger object graph = larger gains from optimizing repeated types names away.
- Prototyping networking (in, lets say, a game)

Once you're done with the networking part, you should definitely use `KnownTypes`. The idea is that both server and client, on startup, register every type that can possibly be sent over the network (you'd probably want to use reflection to find all types that inherit from `IMyGameNetworkMessage`, order them by namespace+name, and then register them to automate the bulk of the work away 😄).
`KnownTypes` is pretty much the improved version of `PersistTypeCache`, because you have full control over what types get a pre defined ID.

There are settings to even combine KnownTypes with the dynamic type caching thing (PersistTypeCache), and/or to forbid sending types that aren't known beforehand.

**Comment by asusralis** [comment]
Thank you for the information, oh wise Rikimaru; I shall go with multiple serializers. I hope you find free time in the future for both Ceras and for your own sake. I don't know why I have such an interest in a relatively benign project like this : )
